INSERT INTO BEAN (BEAN_ID, BEAN_NAME, BEAN_NUMBER) VALUES (1, 'Bean with 64', 64);
INSERT INTO BEAN (BEAN_ID, BEAN_NAME, BEAN_NUMBER) VALUES (2, 'Bean with 128', 128);
INSERT INTO BEAN (BEAN_ID, BEAN_NAME, BEAN_NUMBER) VALUES (3, 'Bean with 128', 256);
INSERT INTO BEAN (BEAN_ID, BEAN_NAME, BEAN_NUMBER) VALUES (4, 'bean with 512', 512);